@startuml 
entity User #e3daff
entity User.email #e3daff
entity User.password #e3daff
entity User.avatar #e3daff

entity Role #e3daff
entity Role.name #e3daff
entity Role.desciption #e3daff

entity Commit #e3daff
entity Commit.id #e3daff
entity Commit.description #e3daff
entity Commit.createdAt #e3daff

entity Annotation #e3daff
entity Annotation.tom #e3daff

entity Text #e3daff
entity Text.content #e3daff
entity Text.title #e3daff

entity Corpus #e3daff
entity Corpus.name #e3daff
entity Corpus.description #e3daff

entity Branch #e3daff
entity Branch.name #e3daff


User.email -d-* User
User.password -d-* User
User.avatar -d-* User

Role.name -r-* Role
Role.desciption -r-* Role

Commit.id -r-* Commit
Commit.description -r-* Commit
Commit.createdAt -r-* Commit

Annotation.tom -u-* Annotation

Text.content -u-* Text
Text.title -l-* Text

Corpus.name -d-* Corpus
Corpus.description -l-* Corpus

Branch.name -l-* Branch


User "(0,*)"-l-"(1,1)" Role
User "0,*"-r-"1,1" Corpus
User "(1,1)"-d-"(0,*)" Commit

Commit "0,*" -r- "1,1" Branch
Commit "1,1" -d- "1,*" Annotation

Corpus "0,*" -d- "1,1" Branch
Corpus "1,1" -d- "0,*" Text

Text "1,1" -l- "0,*" Annotation
@enduml
